### ISSUE TITLE
read me not descriptive 

### ISSUE THREAD

**Issue by raitalharehman** [LunarWatcher/userscripts#3]
Read me not telling that this repo about

**Comment by LunarWatcher** [comment]
So? 

I've been thinking about restructuring the mess of a repo for a while, which would re-locate the readme into various subfolders and allow adding documentation there, but the main readme doesn't need to be more descriptive. 

Additionally, each of the userscripts have descriptions. Documentation all-round is... well, horrible. Most of them either do unnoticeable stuff (no user interaction for an instance), while some others add a single interaction feature that's self-explanatory. No output isn't necessarily the best UX if no action is taken, but that's mainly horrible planning and something that's planned to be fixed in 6-8
